type = "enum@v1"

name = "some_enum"

namespace = "abc.corp.namespace"

description = "some enum description"

version = 1


[variants.A]
name = "A"
value = 1


[variants.B]
name = "B"
description = "Some b variant = 2"
value = 2
