type = "enum@v1"
name = "BasicStrEnum"
namespace = "abc.corp.test"
version = 1

[variants.A]
name = "A"
namespace = "abc.corp.test"
description = "some doc"
value = "a"

[variants.B]
name = "B"
namespace = "abc.corp.test"
value = "b"
