type = "struct@v1"
name = "OperationErrorUnknown"
namespace = "abc.corp.test"
version = 1

[fields.desc]
name = "desc"
namespace = "abc.corp.test"
description = "some nested doc"
type = "string"
optional = false
