type = "struct@v1"
name = "StructWithOneOf"
namespace = "abc.corp.exts"
version = 1

[fields.my_flag]
name = "my_flag"
namespace = "abc.corp.exts"
optional = false

[fields.my_flag.type.compound_type]
kind = "one_of"
ref = "MaybeFlagType"
