type = "struct@v1"
name = "BasicStructWithReadme"
namespace = "abc.corp.test"
description = """
# test
this is a struct description
"""
version = 1

[fields.a]
name = "a"
namespace = "abc.corp.test"
type = "i32"
description = "field a"
optional = false
