[package]
name = "operation-api-sdk"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true


[dependencies]
operation-api-core = { path = "../core" }
operation-api-derives = { path = "../derives" }

[dev-dependencies]
serde_json = "*"
toml = "*"
serde_yaml = "*"
insta = { workspace = true, features = ["yaml"] }
