[package]
name = "operation-api-sdk"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true


[dependencies]
operation-api-core = { path = "../core" }
operation-api-derives = { path = "../derives" }
serde_repr = "*"

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
serde_yaml.workspace = true
insta = { workspace = true, features = ["yaml"] }
