name: Benchmark
on:
  pull_request:
    branches:
      - main
      - v*
  push:
    branches:
      - main
      - v*
      - parser

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Check Performance Regressions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: cargo

      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./target/criterion
          key: benchmark-${{ runner.os }}-${{ github.event.pull_request.number || github.ref }}

      - name: Run benchmark
        run: cargo bench | tee output.txt

      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./target/criterion
          key: benchmark-${{ runner.os }}-${{ github.event.pull_request.number || github.ref }}

      # todo: something with the benchmarks, low priority
