name: Test

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v5

    - uses: actions/cache@v4
      with:
        path: |
          target/
        key: ${{ hashFiles('src/**', 'Cargo.toml', 'Cargo.lock') }}

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: cargo

    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@v1.15.5

    - name: Install cargo-insta
      run: | 
        cargo binstall -y --force cargo-insta

    - name: Cargo Test
      run: |
        cargo insta test --all-features
