name: Test

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache@v4
        with:
          path: |
            target/
          key: ${{ hashFiles('src/**', 'Cargo.toml', 'Cargo.lock') }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: cargo rustfmt

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.15.5

      - name: Install cargo-insta
        run: |
          cargo binstall -y --force cargo-insta

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Test Generation
        run: |
          cargo run -- gen -d examples/gen-a

      - name: Cargo Test
        id: cargo_test
        run: |
          cargo insta test --all-features

      - name: Upload snapshots of failed tests
        if: ${{ failure() && steps.cargo_test.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: failed-snapshots
          path: "**/snapshots/*.snap.new"
